workflows:
  version: 2
  node-multi-build:
    jobs:
      - gally-create-pr
      - test-node-v10:
          requires:
            - gally-create-pr
      - test-node-v8.10:
          requires:
            - gally-create-pr
      - gally-auto-merge:
          requires:
            - gally-create-pr
            - test-node-v10
            - test-node-v8.10
      - release:
          requires:
            - gally-create-pr
            - test-node-v10
            - test-node-v8.10
          filters:
            branches:
              only: master
version: 2
jobs:
  gally-create-pr:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - run: sudo npm i -g gally
      - run: ga promote $CIRCLE_BRANCH
  gally-auto-merge:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - run: sudo npm i -g gally
      - run: ga approve $CIRCLE_BUILD_NUM --condition "base.ref=dev&user.login=dependabot[bot]"
      - run: ga merge $CIRCLE_BUILD_NUM --condition "base.ref=dev&user.login=dependabot[bot]"
  test-node-v10:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - run: npm i
      - run: npm t
      - run:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              npm run coveralls
            fi
  test-node-v8.10:
    docker:
      - image: 'circleci/node:8.10'
    steps:
      - checkout
      - run: npm i
      - run: npm t
  release:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - run: npm i
      - run: npm run semantic-release
